package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON, ACCESS_DENIED, ASK_VIEW_FILES, TELL_VIEW_FILES, HEARTBEAT_REQUEST, HEARTBEAT_RESPONSE, RECHECK_NODE, ASK_HEALTH_CHECK, TELL_HEALTH_CHECK
}
